CREATE OR REPLACE DATABASE TRAINING_DB;

CREATE OR REPLACE SCHEMA TRAINING_DB.RAW;

CREATE OR REPLACE TABLE TRAINING_DB.RAW.SALES(
ID INT,
CUSTOMER STRING,
AMOUNT FLOAT,
SALE_DATE DATE
);
    


insert into sales values (101 , 'Tina' , 34500 , '2025-10-10');

select * from sales